### ISSUE TITLE
Layout を作成する

### ISSUE THREAD

**Issue by yu-san-19** [jscg/jscg.github.io-source#1]
型となる Layout を追加したい。

具体的な構想としては、こんな感じ:
- [x]  Bootstrap 4 を使用する
- [x]  OGP 対応済み
- [x]  Title タグを工夫する
~~各要所ごとに SNS にシェアボタン~~

後で追加するかも。

@1010mark  が Github の作業に慣れるまで、 @yu-san-19 と共同ですることにする。

**Comment by yu-san-19** [comment]
Bootstrap 4 を追加は僕がしますね。

**Comment by yu-san-19** [comment]
Bootstrap 4 とベースとなる Layout を追加しました。

**Comment by yu-san-19** [comment]
OGP設定は @1010mark よろしく。

**Comment by yu-san-19** [comment]
すみません、僕としたことが...
歴史改竄しくじって変な足跡つけてしまった...

**Comment by 1010mark** [comment]
push出来たと思ったらソースコードにミスを発見してしまった。

**Comment by yu-san-19** [comment]
post 部よりも先に index を作って merge した方が良さそう。

**Comment by yu-san-19** [comment]
resolved by #11
