### ISSUE TITLE
Travis CI でPush後に自動でCI回してサイトのアップデートまでする仕組みを作りたい。

### ISSUE THREAD

**Issue by yu-san-19** [jscg/jscg.github.io-source#4]
# 経緯

- 現在は手動で `update-site.sh` を実行して動かしている
- 正直行ってめんどくさい
- その上、PRを merge した後のタイミングを掴むこともできず、不安定になる。

以上の理由から、是非とも実装したい。

# 具体的な案:
1. push, mearge, PR を Travis で感知して CI テストを回す
2. ビルドエラーなどを確認して問題ないことを確認する。
3. ホスティング用リポジトリ: [Junior-Social-Creator-Group/junior-social-creator-group.github.io](https://github.com/Junior-Social-Creator-Group/junior-social-creator-group.github.io) へ push する。

こんな感じでやりたい。

# TODO ⚒ 
- [x] .travis.yml を 追加
- [x] Travis CI のセッティング
~~（必要に応じ）テストコード追加~~ 不要

**Comment by 1010mark** [comment]
とりあえず Travis CI 触った。すごく便利だなこれ。
だがしかし、何件かQiitaの記事とかあさってみたけど、 `git push` 時のテストしか情報が見つからなかった。現実的な実装方法を考える必要がある。

**Comment by yu-san-19** [comment]
@1010mark  そうそうTravis CI のことです。
もうちょっとわかりやすく説明とタイトル変更しておいた。

**Comment by yu-san-19** [comment]
> だがしかし、何件かQiitaの記事とかあさってみたけど、 `git push` 時のテストしか情報が見つからなかった。現実的な実装方法を考える必要がある。

Travis の発火条件は設定をいじらない限り決まっていて、
Push, Opened PR, Maerged PR これぐらい。
`git push` 時しかなかったのはおそらく git push が手軽にできたからかと思う。
デフォルトできちんと PR 周りも感知してくれるはず。

**Comment by yu-san-19** [comment]
一応、基本的なことはこれ見てたらできると思うんだけど、
わからないのが、`after_success`で Github のホスティング用 repo に build して生成された `_site` ディレクトリの中身を push できるかなーっていう所。

権限とかの調整が必要そうで ~~めんどくさい~~ 大変そう。

https://jekyllrb.com/docs/continuous-integration/travis-ci/

**Comment by yu-san-19** [comment]
ちょっと僕の方でこれやってみる。

**Comment by yu-san-19** [comment]
とりあえず、 `bundle exec jekyll build` が失敗しないことを基準でやってみる。

**Comment by yu-san-19** [comment]
Github からの push はこれが参考になりそう。
cf. https://www.tam-tam.co.jp/tipsnote/program/post11795.html

**Comment by yu-san-19** [comment]
これ `after_success` だと masterブランチ以外も deploy される...
```yaml
deploy:
    provider: script
    on:
      branch: master
```
こっちの方がいいな。

**Comment by yu-san-19** [comment]
よし完成。PRへ移る。

**Comment by yu-san-19** [comment]
ちなみに PR を開くと自動でこんな感じに CI が回り始めます。
![2018-10-15 1 13 46](https://user-images.githubusercontent.com/26282705/46919249-a3755100-d017-11e8-9810-9128fb4e45f4.png)

**Comment by yu-san-19** [comment]
クローズした後だけど一応試しに master へ push してみる。

**Comment by yu-san-19** [comment]
残念。

**Comment by yu-san-19** [comment]
普通にこういうのあった 😱 
https://docs.travis-ci.com/user/deployment/pages/

**Comment by 1010mark** [comment]
えぇ…悲しいなぁ

**Comment by yu-san-19** [comment]
@1010mark 
一応コードレビューお願いします 🙇

**Comment by yu-san-19** [comment]
できた。
